# 开发环境配置
server:
  port: 8081

  servlet:
    # 应用的访问路径
    context-path: /

  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.microlittleblog: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次
    maxRetryCount: 5
    # 锁定秒
    lockTime: 600


# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  profiles:
    active: druid

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

  redis:
    # 是否开启redis缓存  true开启   false关闭
    open: false
    database: 0
    host: 127.0.0.1
    port: 6379
    # 密码（默认为空）
    password: 123456
    # 连接超时时长（毫秒）
    timeout: 6000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1000
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 50
      # 连接池中的最小空闲连接
      min-idle: 5

shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math

  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30

  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 1440
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

thread:
  corePoolSize: 50
  maxPoolSize: 200
  queueCapacity: 1000
  keepAliveSeconds: 300

mybatis-plus:
  global-config:
    db-config:
      #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0

debug: true